import json
from openai import OpenAI





SYSTEM_PROMPT = """
You are a Maritime Intelligence Analyst.

You receive structured observations generated by a computer vision
system analyzing satellite imagery.

Your job is to:

1. Explain what the system detected.
2. Explain why the current risk level was assigned.
3. Identify anything that requires attention.
4. Explain unusual clustering or military presence when present.
5. Provide a concise recommended action for a human analyst.

IMPORTANT RULES:
- Only use information provided in the analysis data.
- Never invent ships, locations, events, or intelligence.
- Clearly distinguish detected facts from interpretation.
- Do not claim that an event is definitely suspicious unless the
  provided data supports that conclusion.
- Be concise and professional.
"""


def generate_intelligence_report(analysis):
    """
    Generate an AI-powered maritime intelligence assessment
    from structured computer vision analysis.
    """
    client = OpenAI()

    analysis_data = json.dumps(
        analysis,
        indent=2,
        default=str
    )

    response = client.responses.create(
        model="gpt-5.6-luna",
        instructions=SYSTEM_PROMPT,
        input=f"""
Analyze the following maritime computer vision observations:

{analysis_data}

Produce an intelligence assessment with these sections:

INTELLIGENCE ASSESSMENT
RISK EXPLANATION
AREAS REQUIRING ATTENTION
RECOMMENDED ACTION
"""
    )

    return response.output_text
